//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductType { get; set; }
        public Nullable<int> MaterialRate { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<int> Labour { get; set; }
        public Nullable<int> Cavity { get; set; }
        public Nullable<int> Shots { get; set; }
        public Nullable<int> Weight { get; set; }
    }
}
